version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  typesense:
    image: typesense/typesense:26.0
    ports:
      - '8108:8108'
    volumes:
      - typesense_data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'

volumes:
  redis_data:
  typesense_data:
