// Complete country list for the student settings dropdowns.
// Bangladesh and South Korea are pinned to the top; the rest are alphabetical.

export interface CountryOption {
  value: string
  label: string
  code: string
  flag?: string
  search?: string
}

function flag(code: string): string {
  return `https://flagcdn.com/w40/${code}.png`
}

// Extra terms that help users find a country by a more common name.
const SEARCH_ALIASES: Record<string, string> = {
  Bangladesh: 'bd',
  'South Korea': 'korea korean',
  'North Korea': 'korea korean',
  'United States': 'usa us america',
  'United Kingdom': 'uk england britain',
  UAE: 'united arab emirates',
  'Congo': 'drc dr',
  'Congo, Republic of': 'congo brazzaville',
  "Côte d'Ivoire": 'ivory coast',
  'Czech Republic': 'czechia',
  'Eswatini': 'swaziland',
  'Micronesia': 'federated states of micronesia',
  'Russia': 'russian federation',
  'Sao Tome and Principe': 'são tomé',
  'Saudi Arabia': 'ksa',
  'Syria': 'syrian arab republic',
  'Tanzania': 'tanzania',
  'Timor-Leste': 'east timor',
  'Vietnam': 'viet nam',
  'Vatican City': 'holy see',
  'Laos': 'lao',
  'Turkey': 'turkiye',
}

// [iso-2 code, country name]
const PINNED: [string, string][] = [
  ['bd', 'Bangladesh'],
  ['kr', 'South Korea'],
]

const REST: [string, string][] = [
  ['af', 'Afghanistan'],
  ['al', 'Albania'],
  ['dz', 'Algeria'],
  ['ad', 'Andorra'],
  ['ao', 'Angola'],
  ['ag', 'Antigua and Barbuda'],
  ['ar', 'Argentina'],
  ['am', 'Armenia'],
  ['au', 'Australia'],
  ['at', 'Austria'],
  ['az', 'Azerbaijan'],
  ['bs', 'Bahamas'],
  ['bh', 'Bahrain'],
  ['bb', 'Barbados'],
  ['by', 'Belarus'],
  ['be', 'Belgium'],
  ['bz', 'Belize'],
  ['bj', 'Benin'],
  ['bt', 'Bhutan'],
  ['bo', 'Bolivia'],
  ['ba', 'Bosnia and Herzegovina'],
  ['bw', 'Botswana'],
  ['br', 'Brazil'],
  ['bn', 'Brunei'],
  ['bg', 'Bulgaria'],
  ['bf', 'Burkina Faso'],
  ['bi', 'Burundi'],
  ['kh', 'Cambodia'],
  ['cm', 'Cameroon'],
  ['ca', 'Canada'],
  ['cv', 'Cape Verde'],
  ['cf', 'Central African Republic'],
  ['td', 'Chad'],
  ['cl', 'Chile'],
  ['cn', 'China'],
  ['co', 'Colombia'],
  ['km', 'Comoros'],
  ['cd', 'Congo'],
  ['cg', 'Congo, Republic of'],
  ['cr', 'Costa Rica'],
  ['ci', "Côte d'Ivoire"],
  ['hr', 'Croatia'],
  ['cu', 'Cuba'],
  ['cy', 'Cyprus'],
  ['cz', 'Czech Republic'],
  ['dk', 'Denmark'],
  ['dj', 'Djibouti'],
  ['dm', 'Dominica'],
  ['do', 'Dominican Republic'],
  ['ec', 'Ecuador'],
  ['eg', 'Egypt'],
  ['sv', 'El Salvador'],
  ['gq', 'Equatorial Guinea'],
  ['er', 'Eritrea'],
  ['ee', 'Estonia'],
  ['sz', 'Eswatini'],
  ['et', 'Ethiopia'],
  ['fj', 'Fiji'],
  ['fi', 'Finland'],
  ['fr', 'France'],
  ['ga', 'Gabon'],
  ['gm', 'Gambia'],
  ['ge', 'Georgia'],
  ['de', 'Germany'],
  ['gh', 'Ghana'],
  ['gr', 'Greece'],
  ['gd', 'Grenada'],
  ['gt', 'Guatemala'],
  ['gn', 'Guinea'],
  ['gw', 'Guinea-Bissau'],
  ['gy', 'Guyana'],
  ['ht', 'Haiti'],
  ['hn', 'Honduras'],
  ['hu', 'Hungary'],
  ['is', 'Iceland'],
  ['in', 'India'],
  ['id', 'Indonesia'],
  ['ir', 'Iran'],
  ['iq', 'Iraq'],
  ['ie', 'Ireland'],
  ['il', 'Israel'],
  ['it', 'Italy'],
  ['jm', 'Jamaica'],
  ['jp', 'Japan'],
  ['jo', 'Jordan'],
  ['kz', 'Kazakhstan'],
  ['ke', 'Kenya'],
  ['ki', 'Kiribati'],
  ['kp', 'North Korea'],
  ['kw', 'Kuwait'],
  ['kg', 'Kyrgyzstan'],
  ['la', 'Laos'],
  ['lv', 'Latvia'],
  ['lb', 'Lebanon'],
  ['ls', 'Lesotho'],
  ['lr', 'Liberia'],
  ['ly', 'Libya'],
  ['li', 'Liechtenstein'],
  ['lt', 'Lithuania'],
  ['lu', 'Luxembourg'],
  ['mg', 'Madagascar'],
  ['mw', 'Malawi'],
  ['my', 'Malaysia'],
  ['mv', 'Maldives'],
  ['ml', 'Mali'],
  ['mt', 'Malta'],
  ['mh', 'Marshall Islands'],
  ['mr', 'Mauritania'],
  ['mu', 'Mauritius'],
  ['mx', 'Mexico'],
  ['fm', 'Micronesia'],
  ['md', 'Moldova'],
  ['mc', 'Monaco'],
  ['mn', 'Mongolia'],
  ['me', 'Montenegro'],
  ['ma', 'Morocco'],
  ['mz', 'Mozambique'],
  ['mm', 'Myanmar'],
  ['na', 'Namibia'],
  ['nr', 'Nauru'],
  ['np', 'Nepal'],
  ['nl', 'Netherlands'],
  ['nz', 'New Zealand'],
  ['ni', 'Nicaragua'],
  ['ne', 'Niger'],
  ['ng', 'Nigeria'],
  ['mk', 'North Macedonia'],
  ['no', 'Norway'],
  ['om', 'Oman'],
  ['pk', 'Pakistan'],
  ['pw', 'Palau'],
  ['ps', 'Palestine'],
  ['pa', 'Panama'],
  ['pg', 'Papua New Guinea'],
  ['py', 'Paraguay'],
  ['pe', 'Peru'],
  ['ph', 'Philippines'],
  ['pl', 'Poland'],
  ['pt', 'Portugal'],
  ['qa', 'Qatar'],
  ['ro', 'Romania'],
  ['ru', 'Russia'],
  ['rw', 'Rwanda'],
  ['kn', 'Saint Kitts and Nevis'],
  ['lc', 'Saint Lucia'],
  ['vc', 'Saint Vincent and the Grenadines'],
  ['ws', 'Samoa'],
  ['sm', 'San Marino'],
  ['st', 'Sao Tome and Principe'],
  ['sa', 'Saudi Arabia'],
  ['sn', 'Senegal'],
  ['rs', 'Serbia'],
  ['sc', 'Seychelles'],
  ['sl', 'Sierra Leone'],
  ['sg', 'Singapore'],
  ['sk', 'Slovakia'],
  ['si', 'Slovenia'],
  ['sb', 'Solomon Islands'],
  ['so', 'Somalia'],
  ['za', 'South Africa'],
  ['ss', 'South Sudan'],
  ['es', 'Spain'],
  ['lk', 'Sri Lanka'],
  ['sd', 'Sudan'],
  ['sr', 'Suriname'],
  ['se', 'Sweden'],
  ['ch', 'Switzerland'],
  ['sy', 'Syria'],
  ['tw', 'Taiwan'],
  ['tj', 'Tajikistan'],
  ['tz', 'Tanzania'],
  ['th', 'Thailand'],
  ['tl', 'Timor-Leste'],
  ['tg', 'Togo'],
  ['to', 'Tonga'],
  ['tt', 'Trinidad and Tobago'],
  ['tn', 'Tunisia'],
  ['tr', 'Turkey'],
  ['tm', 'Turkmenistan'],
  ['tv', 'Tuvalu'],
  ['ug', 'Uganda'],
  ['ua', 'Ukraine'],
  ['ae', 'UAE'],
  ['gb', 'United Kingdom'],
  ['us', 'United States'],
  ['uy', 'Uruguay'],
  ['uz', 'Uzbekistan'],
  ['vu', 'Vanuatu'],
  ['va', 'Vatican City'],
  ['ve', 'Venezuela'],
  ['vn', 'Vietnam'],
  ['ye', 'Yemen'],
  ['zm', 'Zambia'],
  ['zw', 'Zimbabwe'],
]

const alphabetical = [...REST].sort((a, b) => a[1].localeCompare(b[1]))

export const COUNTRIES: CountryOption[] = [...PINNED, ...alphabetical].map(([code, name]) => ({
  value: name,
  label: name,
  code,
  flag: flag(code),
  search: SEARCH_ALIASES[name],
}))

// Study destinations offered by Endow Global. South Korea is pinned first.
// Used for the "target countries" picker in study preferences.
export const EDUCATION_DESTINATIONS: string[] = [
  'South Korea',
  'Australia',
  'Canada',
  'China',
  'France',
  'Germany',
  'Ireland',
  'Japan',
  'Malaysia',
  'Netherlands',
  'New Zealand',
  'Singapore',
  'UAE',
  'United Kingdom',
  'United States',
]