// Comprehensive international dialling codes for the phone number field.
// Bangladesh and South Korea are pinned to the top; the rest are alphabetical
// by country name. Country codes are unique (shared +1/+7 groups are one row).

export interface PhoneCodeOption {
  value: string
  label: string
  search: string
  flag: string
}

function flag(code: string): string {
  return `https://flagcdn.com/w40/${code}.png`
}

// [dialling code, iso-2 code, country name(s) for search]
const PINNED: [string, string, string][] = [
  ['+880', 'bd', 'Bangladesh'],
  ['+82', 'kr', 'South Korea'],
]

const REST: [string, string, string][] = [
  ['+93', 'af', 'Afghanistan'],
  ['+355', 'al', 'Albania'],
  ['+213', 'dz', 'Algeria'],
  ['+376', 'ad', 'Andorra'],
  ['+244', 'ao', 'Angola'],
  ['+1', 'us', 'United States Canada Bahamas Barbados Dominica Dominican Republic Grenada Jamaica Saint Kitts and Nevis Saint Lucia Saint Vincent and the Grenadines Trinidad and Tobago'],
  ['+54', 'ar', 'Argentina'],
  ['+374', 'am', 'Armenia'],
  ['+297', 'aw', 'Aruba'],
  ['+61', 'au', 'Australia'],
  ['+43', 'at', 'Austria'],
  ['+994', 'az', 'Azerbaijan'],
  ['+973', 'bh', 'Bahrain'],
  ['+375', 'by', 'Belarus'],
  ['+32', 'be', 'Belgium'],
  ['+501', 'bz', 'Belize'],
  ['+229', 'bj', 'Benin'],
  ['+975', 'bt', 'Bhutan'],
  ['+591', 'bo', 'Bolivia'],
  ['+387', 'ba', 'Bosnia and Herzegovina'],
  ['+267', 'bw', 'Botswana'],
  ['+55', 'br', 'Brazil'],
  ['+673', 'bn', 'Brunei'],
  ['+359', 'bg', 'Bulgaria'],
  ['+226', 'bf', 'Burkina Faso'],
  ['+257', 'bi', 'Burundi'],
  ['+855', 'kh', 'Cambodia'],
  ['+237', 'cm', 'Cameroon'],
  ['+238', 'cv', 'Cape Verde'],
  ['+236', 'cf', 'Central African Republic'],
  ['+235', 'td', 'Chad'],
  ['+56', 'cl', 'Chile'],
  ['+86', 'cn', 'China'],
  ['+57', 'co', 'Colombia'],
  ['+269', 'km', 'Comoros'],
  ['+243', 'cd', 'Congo DRC'],
  ['+242', 'cg', 'Congo'],
  ['+506', 'cr', 'Costa Rica'],
  ['+385', 'hr', 'Croatia'],
  ['+53', 'cu', 'Cuba'],
  ['+357', 'cy', 'Cyprus'],
  ['+420', 'cz', 'Czech Republic'],
  ['+45', 'dk', 'Denmark'],
  ['+253', 'dj', 'Djibouti'],
  ['+593', 'ec', 'Ecuador'],
  ['+20', 'eg', 'Egypt'],
  ['+503', 'sv', 'El Salvador'],
  ['+240', 'gq', 'Equatorial Guinea'],
  ['+291', 'er', 'Eritrea'],
  ['+372', 'ee', 'Estonia'],
  ['+268', 'sz', 'Eswatini'],
  ['+251', 'et', 'Ethiopia'],
  ['+679', 'fj', 'Fiji'],
  ['+358', 'fi', 'Finland'],
  ['+33', 'fr', 'France'],
  ['+241', 'ga', 'Gabon'],
  ['+220', 'gm', 'Gambia'],
  ['+995', 'ge', 'Georgia'],
  ['+49', 'de', 'Germany'],
  ['+233', 'gh', 'Ghana'],
  ['+30', 'gr', 'Greece'],
  ['+590', 'gp', 'Guadeloupe'],
  ['+502', 'gt', 'Guatemala'],
  ['+224', 'gn', 'Guinea'],
  ['+245', 'gw', 'Guinea-Bissau'],
  ['+592', 'gy', 'Guyana'],
  ['+509', 'ht', 'Haiti'],
  ['+504', 'hn', 'Honduras'],
  ['+36', 'hu', 'Hungary'],
  ['+354', 'is', 'Iceland'],
  ['+91', 'in', 'India'],
  ['+62', 'id', 'Indonesia'],
  ['+98', 'ir', 'Iran'],
  ['+964', 'iq', 'Iraq'],
  ['+353', 'ie', 'Ireland'],
  ['+972', 'il', 'Israel'],
  ['+39', 'it', 'Italy'],
  ['+225', 'ci', "Cote d'Ivoire Ivory Coast"],
  ['+81', 'jp', 'Japan'],
  ['+962', 'jo', 'Jordan'],
  ['+7', 'ru', 'Russia Kazakhstan'],
  ['+254', 'ke', 'Kenya'],
  ['+686', 'ki', 'Kiribati'],
  ['+383', 'xk', 'Kosovo'],
  ['+965', 'kw', 'Kuwait'],
  ['+996', 'kg', 'Kyrgyzstan'],
  ['+856', 'la', 'Laos'],
  ['+371', 'lv', 'Latvia'],
  ['+961', 'lb', 'Lebanon'],
  ['+266', 'ls', 'Lesotho'],
  ['+231', 'lr', 'Liberia'],
  ['+218', 'ly', 'Libya'],
  ['+423', 'li', 'Liechtenstein'],
  ['+370', 'lt', 'Lithuania'],
  ['+352', 'lu', 'Luxembourg'],
  ['+261', 'mg', 'Madagascar'],
  ['+265', 'mw', 'Malawi'],
  ['+60', 'my', 'Malaysia'],
  ['+960', 'mv', 'Maldives'],
  ['+223', 'ml', 'Mali'],
  ['+356', 'mt', 'Malta'],
  ['+596', 'mq', 'Martinique'],
  ['+222', 'mr', 'Mauritania'],
  ['+230', 'mu', 'Mauritius'],
  ['+52', 'mx', 'Mexico'],
  ['+691', 'fm', 'Micronesia'],
  ['+373', 'md', 'Moldova'],
  ['+377', 'mc', 'Monaco'],
  ['+976', 'mn', 'Mongolia'],
  ['+382', 'me', 'Montenegro'],
  ['+212', 'ma', 'Morocco'],
  ['+258', 'mz', 'Mozambique'],
  ['+95', 'mm', 'Myanmar'],
  ['+264', 'na', 'Namibia'],
  ['+674', 'nr', 'Nauru'],
  ['+977', 'np', 'Nepal'],
  ['+31', 'nl', 'Netherlands'],
  ['+599', 'cw', 'Curacao Caribbean Netherlands'],
  ['+687', 'nc', 'New Caledonia'],
  ['+64', 'nz', 'New Zealand'],
  ['+505', 'ni', 'Nicaragua'],
  ['+227', 'ne', 'Niger'],
  ['+234', 'ng', 'Nigeria'],
  ['+389', 'mk', 'North Macedonia'],
  ['+47', 'no', 'Norway'],
  ['+968', 'om', 'Oman'],
  ['+92', 'pk', 'Pakistan'],
  ['+680', 'pw', 'Palau'],
  ['+970', 'ps', 'Palestine'],
  ['+507', 'pa', 'Panama'],
  ['+675', 'pg', 'Papua New Guinea'],
  ['+595', 'py', 'Paraguay'],
  ['+51', 'pe', 'Peru'],
  ['+63', 'ph', 'Philippines'],
  ['+48', 'pl', 'Poland'],
  ['+351', 'pt', 'Portugal'],
  ['+974', 'qa', 'Qatar'],
  ['+262', 're', 'Reunion'],
  ['+40', 'ro', 'Romania'],
  ['+250', 'rw', 'Rwanda'],
  ['+685', 'ws', 'Samoa'],
  ['+378', 'sm', 'San Marino'],
  ['+239', 'st', 'Sao Tome and Principe'],
  ['+966', 'sa', 'Saudi Arabia'],
  ['+221', 'sn', 'Senegal'],
  ['+381', 'rs', 'Serbia'],
  ['+248', 'sc', 'Seychelles'],
  ['+232', 'sl', 'Sierra Leone'],
  ['+65', 'sg', 'Singapore'],
  ['+421', 'sk', 'Slovakia'],
  ['+386', 'si', 'Slovenia'],
  ['+677', 'sb', 'Solomon Islands'],
  ['+252', 'so', 'Somalia'],
  ['+27', 'za', 'South Africa'],
  ['+211', 'ss', 'South Sudan'],
  ['+34', 'es', 'Spain'],
  ['+94', 'lk', 'Sri Lanka'],
  ['+249', 'sd', 'Sudan'],
  ['+597', 'sr', 'Suriname'],
  ['+46', 'se', 'Sweden'],
  ['+41', 'ch', 'Switzerland'],
  ['+963', 'sy', 'Syria'],
  ['+886', 'tw', 'Taiwan'],
  ['+992', 'tj', 'Tajikistan'],
  ['+255', 'tz', 'Tanzania'],
  ['+66', 'th', 'Thailand'],
  ['+670', 'tl', 'Timor-Leste'],
  ['+228', 'tg', 'Togo'],
  ['+676', 'to', 'Tonga'],
  ['+216', 'tn', 'Tunisia'],
  ['+90', 'tr', 'Turkey'],
  ['+993', 'tm', 'Turkmenistan'],
  ['+688', 'tv', 'Tuvalu'],
  ['+256', 'ug', 'Uganda'],
  ['+380', 'ua', 'Ukraine'],
  ['+971', 'ae', 'UAE United Arab Emirates'],
  ['+44', 'gb', 'United Kingdom'],
  ['+598', 'uy', 'Uruguay'],
  ['+998', 'uz', 'Uzbekistan'],
  ['+678', 'vu', 'Vanuatu'],
  ['+379', 'va', 'Vatican City'],
  ['+58', 've', 'Venezuela'],
  ['+84', 'vn', 'Vietnam'],
  ['+681', 'wf', 'Wallis and Futuna'],
  ['+967', 'ye', 'Yemen'],
  ['+260', 'zm', 'Zambia'],
  ['+263', 'zw', 'Zimbabwe'],
]

const alphabetical = [...REST].sort((a, b) => a[2].localeCompare(b[2]))

export const PHONE_PREFIXES: PhoneCodeOption[] = [...PINNED, ...alphabetical].map(
  ([value, iso, name]) => ({
    value,
    label: value,
    search: name,
    flag: flag(iso),
  })
)