export const SITE_CONFIG = {
  companyName: 'Endow Global Education',
  shortName: 'Endow Global',
  tagline: 'Education',
  servedCountries: ['South Korea', 'Australia'],
  email: 'contact@endowglobaledu.com',
  phoneBD: '+880 190146 3204',
  phoneBDHref: 'tel:+8801901463204',
  phoneKR: '+82 1057 6725 59',
  phoneKRHref: 'tel:+821057672559',
  address: 'H# 24/1 & 24/2, Level# 8, Endow Global Education, Shyamoli Square, Mirpur Rd, Dhaka',
  logo: '/logo/endoedu.svg',
  logoAlt: 'Endow Global Education',
  social: {
    facebook: 'https://www.facebook.com/endowglobaledu',
    instagram: 'https://www.instagram.com/endowglobaledu',
    x: 'https://x.com/endowglobaledu',
    linkedin: 'https://www.linkedin.com/company/endow-global-education/',
  },
} as const
